name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 💚 Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: 🚧 Install Dependencies
        run: npm ci
      - name: 📦 Build
        run: npm run build
      - name: 🧪 Run Tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test